# Generated by Django 2.1.dev20180404232150 on 2018-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='values',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
